version: '3.9'
services:
  reservationDB:
    image: mongo:latest
    volumes:
      - /dbs/reservationDB/data/lib

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - customer

  customer:
    build: ./customer
    
